logging:
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql: trace
sumfi:
  application:
    datasource:
      master:
        url: mysql://root:admin@localhost:3306/playground?serverTimezone=Asia/Seoul&allowMultiQueries=true
        username: root
        password: admin
      slave:
        url: mysql://root:admin@localhost:3306/playground?serverTimezone=Asia/Seoul&allowMultiQueries=true
        username: root
        password: admin

spring:
  r2dbc:
    url:
      r2dbc: mysql://localhost:3306/playground?serverTimezone=Asia/Seoul&allowMultiQueries=true
      username: root
      password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
        connection.provider_disables_autocommit: true
        default_batch_fetch_size: 200
        cache.use_second_level_cache: true
        cache.use_query_cache: false
        cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
